### PR TITLE
👌 IMPROVE: Add support for doctest_block nodes

### PR DESCRIPTION
**Pull request by zsol**
Currently these are treated like a paragraph. Treating them like a `literal_block` is better.

### CODE REVIEW

**Comment by chrisjsewell** [comment]
Thanks, do you want to look into adding a test?

My only thought though, is that perhaps there should be a warning and/or some hint in the output, that this conversion (and this loss of information) occurred

**Comment by zsol** [comment]
Oh! Hi! :)
Yeah, of course. I can add a warning as well as a test case.

**Comment by zsol** [comment]
Done!

**Review by chrisjsewell — DISMISSED** [review]

**Comment by chrisjsewell** [comment]
Hey @zsol, from the lack of test coverage, I realised your test example wasn't actually a doctest block 😅

So I fixed it, and also added the `pycon` pygment lexer to the output block.

Have a look, and let me know if that looks ok

**Comment by zsol** [comment]
Oh 😆 thanks for fixing :) lgtm

**Review by chrisjsewell — APPROVED** [review]

**Pull request merged**
